// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "speaker.h"

/* ── HP 로컬 상태 변수 (my_tasks.c 정의) ──
 *  GUI 조작 → 로컬 상태만 업데이트.
 *  Main이 @Q 폴링하면 RS485 태스크가 이 값들을 읽어 응답.
 *  HP는 자율 송신하지 않음 (슬레이브). */
extern volatile uint8_t g_rf_power;       /* PWR 슬라이더 0~9 */

lv_obj_t * uic_ImgButton1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_LabelPWR = NULL;
lv_obj_t * ui_LabelNEEDLE = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    // Guard: Slider1/Slider2 already have dedicated handlers.
    // Without this guard, bubbled VALUE_CHANGED from ImgButton1
    // calls lv_slider_get_value() on a non-slider → garbage digits.
    (void)e;
}

void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        /* CHECKED = READY(1), UNCHECKED = STBY(0) */
        extern volatile uint8_t g_gui_ready;
        g_gui_ready = lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED) ? 1U : 0U;

        /* ── 버튼 라벨 텍스트 변경 ── */
        lv_obj_t * label = lv_obj_get_child(ui_ImgButton1, 0);
        if(label) lv_label_set_text(label, g_gui_ready ? "READY" : "STBY");

        /* ── 사운드 출력 ── */
        Speaker_Play(g_gui_ready ? SND_READY : SND_STBY);
        /* g_gui_ready 는 위에서 설정 완료 → Main @Q 폴링 시 응답에 반영 */
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label2, target, "", "");
        /* READY → STBY 자동 전환 */
        extern volatile uint8_t g_gui_ready;
        if (lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED)) {
            lv_obj_clear_state(ui_ImgButton1, LV_STATE_CHECKED);
            lv_obj_invalidate(ui_ImgButton1);  /* 강제 갱신 */
            lv_obj_t * label = lv_obj_get_child(ui_ImgButton1, 0);
            if(label) lv_label_set_text(label, "STBY");
            Speaker_Play(SND_STBY);  /* READY→STBY 전환 사운드 */
        }
        g_gui_ready = 0U;  /* 슬라이더 변경 시 항상 STBY */

        /* PWR 로컬 상태 업데이트 → Main @Q 폴링 시 응답에 반영 */
        g_rf_power = (uint8_t)lv_slider_get_value(target);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label1, target, "", "");
        /* Slider 0..6 → needle depth 0.50..3.50 mm (step 0.50 mm) */
        extern volatile float g_needle_depth_mm;
        int val = lv_slider_get_value(target);
        g_needle_depth_mm = (val + 1) * 0.50f;
        /* READY → STBY 자동 전환 */
        extern volatile uint8_t g_gui_ready;
        if (lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED)) {
            lv_obj_clear_state(ui_ImgButton1, LV_STATE_CHECKED);
            lv_obj_invalidate(ui_ImgButton1);  /* 강제 갱신 */
            lv_obj_t * label = lv_obj_get_child(ui_ImgButton1, 0);
            if(label) lv_label_set_text(label, "STBY");
            Speaker_Play(SND_STBY);  /* READY→STBY 전환 사운드 */
        }
        g_gui_ready = 0U;  /* 슬라이더 변경 시 항상 STBY */
        /* g_needle_depth_mm 은 위에서 설정 완료 → Main @Q 폴링 시 응답에 반영 */
    }
}

/* ═══════════════════════════════════════════════════════════
 *  RS485 → UI 동기화 콜백 (LVGL 스레드에서 50ms 주기 실행)
 *
 *  rs485_process()가 B/R/S/P/N 커맨드 수신 시
 *  로컬 상태를 업데이트하고 g_ui_update_pending=1 설정.
 *  이 타이머가 LVGL 스레드에서 UI를 갱신한다.
 * ═══════════════════════════════════════════════════════════*/
static void ui_rs485_sync_cb(lv_timer_t *timer)
{
    (void)timer;
    extern volatile uint8_t g_ui_update_pending;
    if (!g_ui_update_pending) return;
    g_ui_update_pending = 0;

    extern volatile uint8_t g_gui_ready;
    extern volatile float   g_needle_depth_mm;

    /* ── READY/STBY 버튼 ── */
    if (g_gui_ready) {
        if (!lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED))
            lv_obj_add_state(ui_ImgButton1, LV_STATE_CHECKED);
    } else {
        if (lv_obj_has_state(ui_ImgButton1, LV_STATE_CHECKED))
            lv_obj_clear_state(ui_ImgButton1, LV_STATE_CHECKED);
    }
    lv_obj_invalidate(ui_ImgButton1);
    lv_obj_t *lbl = lv_obj_get_child(ui_ImgButton1, 0);
    if (lbl) lv_label_set_text(lbl, g_gui_ready ? "READY" : "STBY");

    /* ── PWR 슬라이더 (Slider2, 0~9) ── */
    lv_slider_set_value(ui_Slider2, (int32_t)g_rf_power, LV_ANIM_OFF);
    _ui_slider_set_text_value(ui_Label2, ui_Slider2, "", "");

    /* ── NEEDLE 슬라이더 (Slider1, 0~6)
     *   g_needle_depth_mm 0.50~3.50 → slider val 0~6
     *   val = round(depth / 0.5) - 1                  */
    int ndl_val = (int)(g_needle_depth_mm * 2.0f + 0.5f) - 1;
    if (ndl_val < 0) ndl_val = 0;
    if (ndl_val > 6) ndl_val = 6;
    lv_slider_set_value(ui_Slider1, (int32_t)ndl_val, LV_ANIM_OFF);
    _ui_slider_set_text_value(ui_Label1, ui_Slider1, "", "");
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_style_all(ui_Screen1);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE |
        LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE);

    /* ─────────────────────────────────────────────────────────
     * 배경색을 Screen이 아닌 별도 자식 패널에 설정.
     * Screen 자체는 완전 투명 → 어떤 상태(PRESSED/CHECKED/FOCUSED)
     * 변경이 발생해도 화면 배경색이 절대 바뀌지 않음.
     * ───────────────────────────────────────────────────────── */
    lv_obj_t * ui_BgPanel = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_BgPanel);
    lv_obj_set_size(ui_BgPanel, LV_PCT(100), LV_PCT(100));
    lv_obj_set_pos(ui_BgPanel, 0, 0);
    lv_obj_clear_flag(ui_BgPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE |
        LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_obj_set_style_bg_color(ui_BgPanel, lv_color_hex(0x3C3C44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BgPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ImgButton1, 240);
    lv_obj_set_height(ui_ImgButton1, 80);
    lv_obj_set_x(ui_ImgButton1, 2);
    lv_obj_set_y(ui_ImgButton1, 101);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgButton1, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    /* ── 전환 애니메이션 제거 (즉시 변환) ── */
    static lv_style_transition_dsc_t tr_instant;
    static lv_style_prop_t tr_props[] = {LV_STYLE_BG_COLOR, LV_STYLE_SHADOW_COLOR,
        LV_STYLE_SHADOW_OPA, LV_STYLE_SHADOW_WIDTH, LV_STYLE_BORDER_COLOR, 0};
    lv_style_transition_dsc_init(&tr_instant, tr_props, lv_anim_path_linear, 0, 0, NULL);
    lv_obj_set_style_transition(ui_ImgButton1, &tr_instant, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transition(ui_ImgButton1, &tr_instant, LV_PART_MAIN | LV_STATE_CHECKED);

    /* ── STBY state (unchecked) : vivid blue ── */
    lv_obj_set_style_bg_color(ui_ImgButton1, lv_color_hex(0x1E90FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ImgButton1, lv_color_hex(0x1E90FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ImgButton1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ImgButton1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ImgButton1, lv_color_hex(0x60B0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImgButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ── READY state (checked) : vivid red ── */
    lv_obj_set_style_bg_color(ui_ImgButton1, lv_color_hex(0xFF2020), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_ImgButton1, lv_color_hex(0xFF2020), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_ImgButton1, 180, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_ImgButton1, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_ImgButton1, lv_color_hex(0xFF7070), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_ImgButton1, 2, LV_PART_MAIN | LV_STATE_CHECKED);

    /* ── Button label ── */
    lv_obj_t * ui_BtnLabel = lv_label_create(ui_ImgButton1);
    lv_label_set_text(ui_BtnLabel, "STBY");
    lv_obj_center(ui_BtnLabel);
    lv_obj_set_style_text_color(ui_BtnLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnLabel, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 36);
    lv_obj_set_y(ui_Label1, -79);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "3");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFDD203), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -38);
    lv_obj_set_y(ui_Label2, -79);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "5");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFD050E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPWR = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelPWR, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelPWR, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LabelPWR, -77);
    lv_obj_set_y(ui_LabelPWR, 35);
    lv_obj_set_align(ui_LabelPWR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPWR, "PWR");
    lv_obj_set_style_text_color(ui_LabelPWR, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPWR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPWR, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNEEDLE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelNEEDLE, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelNEEDLE, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LabelNEEDLE, 75);
    lv_obj_set_y(ui_LabelNEEDLE, 35);
    lv_obj_set_align(ui_LabelNEEDLE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNEEDLE, "NEEDLE");
    lv_obj_set_style_text_color(ui_LabelNEEDLE, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNEEDLE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNEEDLE, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider2, 0, 9);
    lv_slider_set_value(ui_Slider2, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 11);
    lv_obj_set_height(ui_Slider2, 120);
    lv_obj_set_x(ui_Slider2, -77);
    lv_obj_set_y(ui_Slider2, -50);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x04FC04), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ── Slider2 indicator: bright green glow ── */
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x00FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0x00E000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x00FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider2, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    /* ── Slider2 knob: red (Label2 font color) ── */
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFD050E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0xB00308), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider2, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Slider2, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider2, lv_color_hex(0x1C1C24), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider2, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider2, 200, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider2, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider2, 150, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider2, 24, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider2, 24, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider2, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider2, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_ext_click_area(ui_Slider2, 15);  /* 터치 확장 영역 */

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider1, 0, 6);
    lv_slider_set_value(ui_Slider1, 3, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 12);
    lv_obj_set_height(ui_Slider1, 120);
    lv_obj_set_x(ui_Slider1, 75);
    lv_obj_set_y(ui_Slider1, -50);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x05FD05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ── Slider1 indicator: bright green glow ── */
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x00FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider1, lv_color_hex(0x00E000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider1, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider1, lv_color_hex(0x00FF40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider1, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Slider1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    /* ── Slider1 knob: yellow (Label1 font color) ── */
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFDD203), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider1, lv_color_hex(0xB09502), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Slider1, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Slider1, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0x1C1C24), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 200, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Slider1, 8, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Slider1, 150, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider1, 24, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider1, 24, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider1, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider1, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_ext_click_area(ui_Slider1, 15);  /* 터치 확장 영역 */

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    /* Screen1 이벤트 제거 — 배경색 변경 방지 */
    uic_ImgButton1 = ui_ImgButton1;

    /* RS485 수신 → UI 동기화 타이머 (50ms 주기, LVGL 스레드에서 실행) */
    lv_timer_create(ui_rs485_sync_cb, 50, NULL);
}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_ImgButton1 = NULL;
    ui_ImgButton1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Slider2 = NULL;
    ui_Slider1 = NULL;
    ui_LabelPWR = NULL;
    ui_LabelNEEDLE = NULL;

}
